### ISSUE TITLE
Migrate project dependencies to using Version Catalogs

### ISSUE THREAD

**Issue by snaik20** [TeamNewPipe/NewPipe#10927]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Currently, the project manages dependencies by declaring them directly within the `build.gradle` file. This approach, while functional, can become cumbersome and difficult to maintain as the project grows and the number of dependencies increases.

This feature proposes migrating dependency management to Version Catalogs. Version catalogs are a centralized location within the Gradle build system to store and manage all project dependencies.

### Why do you want this feature?

Version catalogs offer several advantages over declaring dependencies directly in build.gradle: https://developer.android.com/build/migrate-to-catalogs

**Comment by JL0000** [comment]
There doesn't seem to be a PR for this issue, so I want to try to implement this.

**Comment by litetex** [comment]
Sorry but I have to completely disagree on this topic:

>  can become cumbersome and difficult to maintain as the project grows and the number of dependencies increases

That's not a scalability problem nor difficult to maintain, otherwise we would have encountered difficulties for a long time.

It's also a lot better to remove dependencies if possible (for example if you use one file from a library copy that over instead of adding a 500KB lib).

> Version catalogs offer several advantages over declaring dependencies directly in build.gradle

Please point these out because currently I don't see them for this project.

<details><summary>I had a look at Google's claimed "advantages"</summary>

> makes managing dependencies and plugins easier when you have multiple modules
> Instead of hardcoding dependency names and versions in individual build files

Not affected - We don't have multiple modules

> and updating each entry whenever you need to upgrade a dependency

We should get a automated dependency update tool like Renovate for this

> central version catalog of dependencies that various modules can reference in a type-safe way with Android Studio assistance

Not sure what's meant with type-safe because currently we use a string and the new way is also a string...
Also nobody needs Android Studio "assistance" to increment a version number.

</details>


I just had a look at [the implementation of this](https://github.com/TeamNewPipe/NewPipe/pull/12706/files) and I personally find it a lot easier to read through

``build.gradle``
```groovy
dependencies {
/** AndroidX **/
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.documentfile:documentfile:1.0.1'
    implementation 'androidx.fragment:fragment-ktx:1.6.2'
}
```

as opposed to the new way:

``build.gradle.kts``
```kotlin
dependencies {
    /** AndroidX **/
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.cardview)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.core)
    implementation(libs.androidx.documentfile)
}
```

``libs.versions.toml``
```toml
[versions]
acra = "5.11.3"
agp = "8.13.0"
appcompat = "1.7.1"
assertj = "3.24.2"
autoservice = "1.1.1"
bridge = "v2.0.2"
cardview = "1.0.0"
checkstyle = "10.12.1"
constraintlayout = "2.1.4"
...

[libraries]
acra-core = { module = "ch.acra:acra-core", version.ref = "acra" }
android-desugar = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
...
```
