### ISSUE TITLE
Add a tool to automatically create dependency updates

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipe#6343]
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
More like a meta issue...

I recently checked if NewPipe is using something to automatically update dependencies (or at least create PR) but I couldn't find anything.
It may be wise to use a dependency update tool such as (if you want the exact reasons take a look at there docs 😉):
* [dependabot](https://dependabot.com/) - [related GitHub docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates)
* [renovate](https://github.com/renovatebot/renovate) 

#### Is your feature request related to a problem? Please describe it
Currently it has to be checked by hand if dependencies are upgradeable. A dependency update tool would do that automatically.

#### Additional context
Dependabot sample file (works also for the extractor):
```yml
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "*"
    # GitHub actions are using git tags (v1 = v1.2 = v1.2.3) which should be compatible until a major change is performed
    update-types: 
    - "version-update:semver-minor"
    - "version-update:semver-patch"
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
```

I tested the changes on a fork and currently [10 Dependencies of NewPipe](https://github.com/litetex/NewPipe/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies) and [5 of NewPipeExtractor](https://github.com/litetex/NewPipeExtractor/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies) are upgradeable
